package com.sizzler.common.utils;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by IntelliJ IDEA. User: xiangli Date: 10/20/11 Time: 11:59 AM To
 * change this template use File | Settings | File Templates.
 */
public class CountryUtil {
  private static Map<String, String> CountryMap = new HashMap<String, String>();

  static {
    CountryMap.put("AF", "Afghanistan");
    CountryMap.put("AX", "Aland Islands");
    CountryMap.put("AL", "Albania");
    CountryMap.put("DZ", "Algeria");
    CountryMap.put("AS", "American Samoa");
    CountryMap.put("AD", "Andorra");
    CountryMap.put("AO", "Angola");
    CountryMap.put("AI", "Anguilla");
    CountryMap.put("AQ", "Antarctica");
    CountryMap.put("AG", "Antigua and Barbuda");
    CountryMap.put("AR", "Argentina");
    CountryMap.put("AM", "Armenia");
    CountryMap.put("AW", "Aruba");
    CountryMap.put("AC", "Ascension Island");
    CountryMap.put("AU", "Australia");
    CountryMap.put("AT", "Austria");
    CountryMap.put("AZ", "Azerbaijan");
    CountryMap.put("BS", "Bahamas");
    CountryMap.put("BH", "Bahrain");
    CountryMap.put("BB", "Barbados");
    CountryMap.put("BD", "Bangladesh");
    CountryMap.put("BY", "Belarus");
    CountryMap.put("BE", "Belgium");
    CountryMap.put("BZ", "Belize");
    CountryMap.put("BJ", "Benin");
    CountryMap.put("BM", "Bermuda");
    CountryMap.put("BT", "Bhutan");
    CountryMap.put("BW", "Botswana");
    CountryMap.put("BO", "Bolivia");
    CountryMap.put("BA", "Bosnia and Herzegovina");
    CountryMap.put("BV", "Bouvet Island");
    CountryMap.put("BR", "Brazil");
    CountryMap.put("IO", "British Indian Ocean Territory");
    CountryMap.put("BN", "Brunei Darussalam");
    CountryMap.put("BG", "Bulgaria");
    CountryMap.put("BF", "Burkina Faso");
    CountryMap.put("BI", "Burundi");
    CountryMap.put("KH", "Cambodia");
    CountryMap.put("CM", "Cameroon");
    CountryMap.put("CA", "Canada");
    CountryMap.put("CV", "Cape Verde");
    CountryMap.put("KY", "Cayman Islands");
    CountryMap.put("CF", "Central African Republic");
    CountryMap.put("TD", "Chad");
    CountryMap.put("CL", "Chile");
    CountryMap.put("CN", "China");
    CountryMap.put("CX", "Christmas Island");
    CountryMap.put("CC", "Cocos (Keeling) Islands");
    CountryMap.put("CO", "Colombia");
    CountryMap.put("KM", "Comoros");
    CountryMap.put("CG", "Congo");
    CountryMap.put("CD", "Congo, Democratic Republic");
    CountryMap.put("CK", "Cook Islands");
    CountryMap.put("CR", "Costa Rica");
    CountryMap.put("CI", "Cote D'Ivoire (Ivory Coast)");
    CountryMap.put("HR", "Croatia (Hrvatska)");
    CountryMap.put("CU", "Cuba");
    CountryMap.put("CY", "Cyprus");
    CountryMap.put("CZ", "Czech Republic");
    CountryMap.put("CS", "Czechoslovakia (former)");
    CountryMap.put("DK", "Denmark");
    CountryMap.put("DJ", "Djibouti");
    CountryMap.put("DM", "Dominica");
    CountryMap.put("DO", "Dominican Republic");
    CountryMap.put("TP", "East Timor");
    CountryMap.put("EC", "Ecuador");
    CountryMap.put("EG", "Egypt");
    CountryMap.put("SV", "El Salvador");
    CountryMap.put("GQ", "Equatorial Guinea");
    CountryMap.put("ER", "Eritrea");
    CountryMap.put("EE", "Estonia");
    CountryMap.put("ET", "Ethiopia");
    CountryMap.put("FK", "Falkland Islands (Malvinas)");
    CountryMap.put("FO", "Faroe Islands");
    CountryMap.put("FJ", "Fiji");
    CountryMap.put("FI", "Finland");
    CountryMap.put("FR", "France");
    CountryMap.put("FX", "France, Metropolitan");
    CountryMap.put("GF", "French Guiana");
    CountryMap.put("PF", "French Polynesia");
    CountryMap.put("TF", "French Southern Territories");
    CountryMap.put("MK", "F.Y.R.O.M. (Macedonia)");
    CountryMap.put("GA", "Gabon");
    CountryMap.put("GM", "Gambia");
    CountryMap.put("GE", "Georgia");
    CountryMap.put("DE", "Germany");
    CountryMap.put("GH", "Ghana");
    CountryMap.put("GI", "Gibraltar");
    CountryMap.put("GB", "Great Britain (UK)");
    CountryMap.put("GR", "Greece");
    CountryMap.put("GL", "Greenland");
    CountryMap.put("GD", "Grenada");
    CountryMap.put("GP", "Guadeloupe");
    CountryMap.put("GU", "Guam");
    CountryMap.put("GT", "Guatemala");
    CountryMap.put("GN", "Guinea");
    CountryMap.put("GW", "Guinea");
    CountryMap.put("GY", "Guyana");
    CountryMap.put("HT", "Haiti");
    CountryMap.put("HM", "Heard and McDonald Islands");
    CountryMap.put("HN", "Honduras");
    CountryMap.put("HK", "Hong Kong");
    CountryMap.put("HU", "Hungary");
    CountryMap.put("IS", "Iceland");
    CountryMap.put("IN", "India");
    CountryMap.put("ID", "Indonesia");
    CountryMap.put("IR", "Iran");
    CountryMap.put("IQ", "Iraq");
    CountryMap.put("IE", "Ireland");
    CountryMap.put("IL", "Israel");
    CountryMap.put("IM", "Isle of Man");
    CountryMap.put("IT", "Italy");
    CountryMap.put("JE", "Jersey");
    CountryMap.put("JM", "Jamaica");
    CountryMap.put("JP", "Japan");
    CountryMap.put("JO", "Jordan");
    CountryMap.put("KZ", "Kazakhstan");
    CountryMap.put("KE", "Kenya");
    CountryMap.put("KI", "Kiribati");
    CountryMap.put("KP", "Korea (North)");
    CountryMap.put("KR", "Korea (South)");
    CountryMap.put("KW", "Kuwait");
    CountryMap.put("KG", "Kyrgyzstan");
    CountryMap.put("LA", "Laos");
    CountryMap.put("LV", "Latvia");
    CountryMap.put("LB", "Lebanon");
    CountryMap.put("LI", "Liechtenstein");
    CountryMap.put("LR", "Liberia");
    CountryMap.put("LY", "Libya");
    CountryMap.put("LS", "Lesotho");
    CountryMap.put("LT", "Lithuania");
    CountryMap.put("LU", "Luxembourg");
    CountryMap.put("MO", "Macau");
    CountryMap.put("MG", "Madagascar");
    CountryMap.put("MW", "Malawi");
    CountryMap.put("MY", "Malaysia");
    CountryMap.put("MV", "Maldives");
    CountryMap.put("ML", "Mali");
    CountryMap.put("MT", "Malta");
    CountryMap.put("MH", "Marshall Islands");
    CountryMap.put("MQ", "Martinique");
    CountryMap.put("MR", "Mauritania");
    CountryMap.put("MU", "Mauritius");
    CountryMap.put("YT", "Mayotte");
    CountryMap.put("MX", "Mexico");
    CountryMap.put("FM", "Micronesia");
    CountryMap.put("MD", "Moldova");
    CountryMap.put("MC", "Monaco");
    CountryMap.put("ME", "Montenegro");
    CountryMap.put("MS", "Montserrat");
    CountryMap.put("MA", "Morocco");
    CountryMap.put("MZ", "Mozambique");
    CountryMap.put("MM", "Myanmar");
    CountryMap.put("NA", "Namibia");
    CountryMap.put("NR", "Nauru");
    CountryMap.put("NP", "Nepal");
    CountryMap.put("NL", "Netherlands");
    CountryMap.put("AN", "Netherlands Antilles");
    CountryMap.put("NT", "Neutral Zone");
    CountryMap.put("NC", "New Caledonia");
    CountryMap.put("NZ", "New Zealand (Aotearoa)");
    CountryMap.put("NI", "Nicaragua");
    CountryMap.put("NE", "Niger");
    CountryMap.put("NG", "Nigeria");
    CountryMap.put("NU", "Niue");
    CountryMap.put("NF", "Norfolk Island");
    CountryMap.put("MP", "Northern Mariana Islands");
    CountryMap.put("NO", "Norway");
    CountryMap.put("OM", "Oman");
    CountryMap.put("PK", "Pakistan");
    CountryMap.put("PW", "Palau");
    CountryMap.put("PS", "Palestinian Territory, Occupied");
    CountryMap.put("PA", "Panama");
    CountryMap.put("PG", "Papua New Guinea");
    CountryMap.put("PY", "Paraguay");
    CountryMap.put("PE", "Peru");
    CountryMap.put("PH", "Philippines");
    CountryMap.put("PN", "Pitcairn");
    CountryMap.put("PL", "Poland");
    CountryMap.put("PT", "Portugal");
    CountryMap.put("PR", "Puerto Rico");
    CountryMap.put("QA", "Qatar");
    CountryMap.put("RE", "Reunion");
    CountryMap.put("RO", "Romania");
    CountryMap.put("RU", "Russian Federation");
    CountryMap.put("RW", "Rwanda");
    CountryMap.put("GS", "S. Georgia and S. Sandwich Isls.");
    CountryMap.put("KN", "Saint Kitts and Nevis");
    CountryMap.put("LC", "Saint Lucia");
    CountryMap.put("VC", "Saint Vincent & the Grenadines");
    CountryMap.put("WS", "Samoa");
    CountryMap.put("SM", "San Marino");
    CountryMap.put("ST", "Sao Tome and Principe");
    CountryMap.put("SA", "Saudi Arabia");
    CountryMap.put("SN", "Senegal");
    CountryMap.put("RS", "Serbia");
    CountryMap.put("SC", "Seychelles");
    CountryMap.put("SL", "Sierra Leone");
    CountryMap.put("SG", "Singapore");
    CountryMap.put("SI", "Slovenia");
    CountryMap.put("SK", "Slovak Republic");
    CountryMap.put("SB", "Solomon Islands");
    CountryMap.put("SO", "Somalia");
    CountryMap.put("ZA", "South Africa");
    CountryMap.put("GS", "S. Georgia and S. Sandwich Isls.");
    CountryMap.put("ES", "Spain");
    CountryMap.put("LK", "Sri Lanka");
    CountryMap.put("SH", "St. Helena");
    CountryMap.put("PM", "St. Pierre and Miquelon");
    CountryMap.put("SD", "Sudan");
    CountryMap.put("SR", "Suriname");
    CountryMap.put("SJ", "Svalbard & Jan Mayen Islands");
    CountryMap.put("SZ", "Swaziland");
    CountryMap.put("SE", "Sweden");
    CountryMap.put("CH", "Switzerland");
    CountryMap.put("SY", "Syria");
    CountryMap.put("TW", "Taiwan");
    CountryMap.put("TJ", "Tajikistan");
    CountryMap.put("TZ", "Tanzania");
    CountryMap.put("TH", "Thailand");
    CountryMap.put("TG", "Togo");
    CountryMap.put("TK", "Tokelau");
    CountryMap.put("TO", "Tonga");
    CountryMap.put("TT", "Trinidad and Tobago");
    CountryMap.put("TN", "Tunisia");
    CountryMap.put("TR", "Turkey");
    CountryMap.put("TM", "Turkmenistan");
    CountryMap.put("TC", "Turks and Caicos Islands");
    CountryMap.put("TV", "Tuvalu");
    CountryMap.put("UG", "Uganda");
    CountryMap.put("UA", "Ukraine");
    CountryMap.put("AE", "United Arab Emirates");
    CountryMap.put("UK", "United Kingdom");
    CountryMap.put("US", "United States");
    CountryMap.put("UM", "US Minor Outlying Islands");
    CountryMap.put("UY", "Uruguay");
    CountryMap.put("SU", "USSR (former)");
    CountryMap.put("UZ", "Uzbekistan");
    CountryMap.put("VU", "Vanuatu");
    CountryMap.put("VA", "Vatican City State (Holy See)");
    CountryMap.put("VE", "Venezuela");
    CountryMap.put("VN", "Viet Nam");
    CountryMap.put("VG", "British Virgin Islands");
    CountryMap.put("VI", "Virgin Islands (U.S.)");
    CountryMap.put("WF", "Wallis and Futuna Islands");
    CountryMap.put("EH", "Western Sahara");
    CountryMap.put("YE", "Yemen");
    CountryMap.put("YU", "Yugoslavia (former)");
    CountryMap.put("ZM", "Zambia");
    CountryMap.put("ZR", "Zaire");
    CountryMap.put("ZW", "Zimbabwe");
  }

  public static String getCountry(String countryCode) {
    String country = null;
    country = CountryMap.get(countryCode);
    if (country == null)
      country = "UNKNOWN CODE:(" + countryCode + ")";
    return country;
  }
}
